title: Sam Holmberg
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
palette: blue
favicon: '/images/favicon.png'
header:
  title: Sam Holmberg
  tagline: Software Engineer
  tagline2: Software Artist
  logo_img: images/logo.png
  logo_img_alt: SH
  background_img: images/home-bg.jpg
  has_nav: true
  nav_links:
    - label: Blog
      url: /
      style: link
    - label: Resume
      url: /resume
      style: link
    - label: About
      url: /about
      style: link
    - label: Projects
      url: /projects
      style: link
    - label: Contact
      url: /contact
      style: link
  has_social: true
  social_links:
    - label: Instagram
      url: 'https://www.instagram.com/sholmberg_/'
      style: icon
      icon_class: instagram
      new_window: true
    - label: GitHub
      url: 'https://github.com/Esaych'
      style: icon
      icon_class: github
      new_window: true
    - label: LinkedIn
      url: 'https://www.linkedin.com/in/samuel-holmberg/'
      style: icon
      icon_class: linkedin
      new_window: true
footer:
  content: >-
    &copy; Stackbit. All rights reserved. This site was created with <a
    href="https://www.stackbit.com/?utm_source=deployed-footer" target="_blank"
    rel="noopener">Stackbit</a>. Super easy and totally recommend it. Create one
    <a
    href="https://app.stackbit.com/create?theme=fjord&utm_source=deployed-footer"
    target="_blank" rel="noopener">for yourself!</a>
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
domain: 'https://sam-dev-15e8b.netlify.app'
